version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/staticfiles
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=0
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build: ./nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - static_volume:/home/app/staticfiles:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  uptime_kuma_data:
